using System.Collections.Generic;
using UnityEngine;

[RequireComponent(typeof(Rigidbody))]
[DisallowMultipleComponent]
public class WindReceiver : MonoBehaviour
{
    [Header("Wind Receiver Settings")]
    [Tooltip("How sensitive the rigidbody is to wind forces.")]
    [SerializeField] private float windSensitivity = 1f;

    [Header("Debug Status (Read-Only)")]
    [SerializeField] private Vector3 currentGlobalWind;
    [SerializeField] private Vector3 currentLocalWind;
    [SerializeField] private Vector3 currentTotalWindForce;
    [SerializeField] private int activeWindAreasCount;

    [Tooltip("Toggle wind physics without disabling the component.")]
    [SerializeField] private bool windEnabled = false;

    private Rigidbody rb;
    private readonly List<WindArea> activeWindAreas = new List<WindArea>();

    private void Awake()
    {
        rb = GetComponent<Rigidbody>();
    }

    private void FixedUpdate()
    {
        // Disabilitato temporaneamente di default per evitare fastidi durante i test
        if (!windEnabled) return;

        // 1. Calculate Global Wind Force
        currentGlobalWind = Vector3.zero;
        if (WindManager.Instance == null)
        {
            // Crea automaticamente il WindManager nella scena se manca
            GameObject wmObj = new GameObject("WindManager_AutoGenerated", typeof(WindManager));
            Debug.Log("WindReceiver: WindManager non trovato nella scena. Creato automaticamente.");
        }

        if (WindManager.Instance != null)
        {
            currentGlobalWind = WindManager.Instance.GetGlobalWind(transform.position);
        }

        // 2. Calculate Local Wind Force from active areas (pruning destroyed ones)
        currentLocalWind = Vector3.zero;
        for (int i = activeWindAreas.Count - 1; i >= 0; i--)
        {
            if (activeWindAreas[i] == null)
            {
                activeWindAreas.RemoveAt(i);
                continue;
            }
            currentLocalWind += activeWindAreas[i].GetLocalWind(transform.position);
        }
        activeWindAreasCount = activeWindAreas.Count;

        // 3. Sum up and apply wind force
        currentTotalWindForce = (currentGlobalWind + currentLocalWind) * windSensitivity;

        if (currentTotalWindForce.magnitude > 0.001f)
        {
            rb.AddForce(currentTotalWindForce, ForceMode.Force);
        }
    }

    /// <summary>
    /// Registers a local wind area when the drone enters it.
    /// </summary>
    public void RegisterWindArea(WindArea area)
    {
        if (area != null && !activeWindAreas.Contains(area))
        {
            activeWindAreas.Add(area);
        }
    }

    /// <summary>
    /// Unregisters a local wind area when the drone exits it.
    /// </summary>
    public void UnregisterWindArea(WindArea area)
    {
        if (area != null && activeWindAreas.Contains(area))
        {
            activeWindAreas.Remove(area);
        }
    }
}
